var searchData=
[
  ['cmc_2ec_4',['cmc.c',['../cmc_8c.html',1,'']]],
  ['cmc_2eh_5',['cmc.h',['../cmc_8h.html',1,'']]],
  ['cmc_5fdecrypt_6',['cmc_decrypt',['../cmc_8h.html#a102e689c3fad7f22d0c9e9fcb9558359',1,'cmc_decrypt(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c'],['../cmc_8c.html#a102e689c3fad7f22d0c9e9fcb9558359',1,'cmc_decrypt(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c']]],
  ['cmc_5fdecrypt_5fperform_7',['cmc_decrypt_perform',['../cmc_8h.html#ac8ae73b1e0aa898447f06c9d8d5668bc',1,'cmc_decrypt_perform(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c'],['../cmc_8c.html#ac8ae73b1e0aa898447f06c9d8d5668bc',1,'cmc_decrypt_perform(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c']]],
  ['cmc_5fencrypt_8',['cmc_encrypt',['../cmc_8h.html#a6d5b11c49f4f49564a55bfeb65defa82',1,'cmc_encrypt(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c'],['../cmc_8c.html#a6d5b11c49f4f49564a55bfeb65defa82',1,'cmc_encrypt(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c']]],
  ['cmc_5fencrypt_5fperform_9',['cmc_encrypt_perform',['../cmc_8h.html#a8bdb06d4bf12c8c7bb77e28922a4a898',1,'cmc_encrypt_perform(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c'],['../cmc_8c.html#a8bdb06d4bf12c8c7bb77e28922a4a898',1,'cmc_encrypt_perform(unsigned long long tweak, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;cmc.c']]]
];
