var searchData=
[
  ['xts_2ec_59',['xts.c',['../xts_8c.html',1,'']]],
  ['xts_2eh_60',['xts.h',['../xts_8h.html',1,'']]],
  ['xts_5fdecrypt_61',['xts_decrypt',['../xts_8h.html#a62006a7e34cebca347d269f9b217c55c',1,'xts_decrypt(unsigned long long sector, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c'],['../xts_8c.html#a62006a7e34cebca347d269f9b217c55c',1,'xts_decrypt(unsigned long long sector, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c']]],
  ['xts_5fdecrypt_5fperform_62',['xts_decrypt_perform',['../xts_8h.html#acebca9a858ccfefd05972e130723596e',1,'xts_decrypt_perform(unsigned long long sector, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c'],['../xts_8c.html#acebca9a858ccfefd05972e130723596e',1,'xts_decrypt_perform(unsigned long long sector, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c']]],
  ['xts_5fencrypt_63',['xts_encrypt',['../xts_8h.html#a539013e0ea1f89eefb0c59daafd71a3e',1,'xts_encrypt(unsigned long long sector, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c'],['../xts_8c.html#a539013e0ea1f89eefb0c59daafd71a3e',1,'xts_encrypt(unsigned long long sector, const unsigned char *in, unsigned long blocks, const unsigned char *data_key, const unsigned char *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c']]],
  ['xts_5fencrypt_5fperform_64',['xts_encrypt_perform',['../xts_8h.html#ae5e0f0faaefc531045547064ffa0a2a9',1,'xts_encrypt_perform(unsigned long long sector, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c'],['../xts_8c.html#ae5e0f0faaefc531045547064ffa0a2a9',1,'xts_encrypt_perform(unsigned long long sector, const unsigned char *in, unsigned long blocks, const KEY *data_key, const KEY *tweak_key, unsigned char *out, const BLOCK_CIPHER *cipher):&#160;xts.c']]],
  ['xtsp_5ftweak_5finit_65',['xtsp_tweak_init',['../xts_8c.html#afc36bc8b7f278ca30a59a484744858e6',1,'xts.c']]]
];
